# Generated by Django 2.1.3 on 2020-04-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('marking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GenericQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('question', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('t', 'Text'), ('m', 'Multiple Choice')], default='t', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(help_text='Enter your answer:', max_length=300)),
                ('marking', models.CharField(choices=[('c', 'Correct'), ('i', 'Incorrect'), ('p', 'Partial')], default='i', max_length=1)),
                ('points', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Game')),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.User')),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('generic_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='quiz.GenericQuestion')),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='textresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.User'),
        ),
        migrations.AddField(
            model_name='genericquestion',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Round'),
        ),
        migrations.AddField(
            model_name='game',
            name='currentQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.GenericQuestion'),
        ),
        migrations.AddField(
            model_name='game',
            name='currentRound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Round'),
        ),
        migrations.AddField(
            model_name='game',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_leader', to='quiz.User'),
        ),
        migrations.AlterUniqueTogether(
            name='userscore',
            unique_together={('user', 'game')},
        ),
        migrations.AddField(
            model_name='textresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.TextQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='textresponse',
            unique_together={('question', 'user', 'game')},
        ),
    ]
