# Generated by Django 2.1.3 on 2020-04-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('currentScreen', models.CharField(choices=[('gs', 'Game Start'), ('qs', 'Quiz Start'), ('qe', 'Quiz End'), ('rs', 'Round Start'), ('re', 'Round End'), ('qa', 'Question Answering'), ('qm', 'Question Marking')], default='gs', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='GenericQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('t', 'Text'), ('m', 'Multiple Choice'), ('i', 'Image')], default='t', max_length=1)),
                ('detail_object_id', models.IntegerField(blank=True, null=True)),
                ('detail_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Quiz')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TextResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(help_text='Enter your answer:', max_length=500)),
                ('marking', models.CharField(choices=[('c', 'Correct'), ('i', 'Incorrect'), ('p', 'Partial')], default='i', max_length=1)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.TextQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('connected', models.BooleanField(default=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Game')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.User')),
            ],
        ),
        migrations.AddField(
            model_name='textresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.User'),
        ),
        migrations.AddField(
            model_name='genericquestion',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Round'),
        ),
        migrations.AddField(
            model_name='game',
            name='currentQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.GenericQuestion'),
        ),
        migrations.AddField(
            model_name='game',
            name='currentQuiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='game',
            name='currentRound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Round'),
        ),
        migrations.AddField(
            model_name='game',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_leader', to='quiz.User'),
        ),
        migrations.AlterUniqueTogether(
            name='userscore',
            unique_together={('user', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='textresponse',
            unique_together={('question', 'user', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='genericquestion',
            unique_together={('number', 'round')},
        ),
    ]
