# Generated by Django 2.1.3 on 2020-04-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genericquestion',
            unique_together={('detail_content_type', 'detail_object_id'), ('number', 'round')},
        ),
    ]
