# Generated by Django 2.1.3 on 2020-04-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userscore',
            unique_together={('user', 'game')},
        ),
    ]
