# Generated by Django 2.1.3 on 2020-04-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='answer', max_length=300),
            preserve_default=False,
        ),
    ]
