# Generated by Django 2.1.3 on 2020-04-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='textresponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
