# Generated by Django 2.1.3 on 2020-04-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200423_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textresponse',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
