# Generated by Django 2.1.3 on 2020-04-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_game_marking'),
    ]

    operations = [
        migrations.AddField(
            model_name='textresponse',
            name='marking',
            field=models.CharField(choices=[('c', 'Correct'), ('i', 'Incorrect'), ('p', 'Partial')], default='i', max_length=1),
        ),
        migrations.AddField(
            model_name='textresponse',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
