# Generated by Django 2.1.3 on 2020-04-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200424_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
