# Generated by Django 2.1.3 on 2020-04-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200428_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textresponse',
            name='response',
            field=models.CharField(default='', help_text='Enter your answer:', max_length=500),
        ),
    ]
