# Generated by Django 2.1.3 on 2020-04-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_user_connected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='marking',
        ),
        migrations.AddField(
            model_name='game',
            name='currentQuiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='game',
            name='current_screen',
            field=models.CharField(choices=[('gs', 'Game Start'), ('qs', 'Quiz Start'), ('qe', 'Quiz End'), ('rs', 'Round Start'), ('re', 'Round End'), ('qa', 'Question Answering'), ('qm', 'Question Marking')], default='gs', max_length=2),
        ),
    ]
