# Generated by Django 2.1.3 on 2020-04-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200424_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current_screen',
            new_name='currentScreen',
        ),
    ]
