# Generated by Django 2.1.3 on 2020-05-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200430_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.MultipleChoiceQuestion'),
        ),
    ]
