# Generated by Django 2.1.3 on 2020-04-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200424_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='currentScreen',
            field=models.CharField(choices=[('gs', 'Game Start'), ('qs', 'Quiz Start'), ('qe', 'Quiz End'), ('rs', 'Round Start'), ('re', 'Round End'), ('qa', 'Question Answering'), ('qm', 'Question Marking')], default='gs', max_length=2),
        ),
    ]
