# Generated by Django 2.1.3 on 2020-05-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200501_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericquestion',
            options={'ordering': ['round', 'number']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['quiz__number', 'number']},
        ),
        migrations.AlterField(
            model_name='imagequestion',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
