# Generated by Django 2.1.3 on 2020-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200502_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
