# Generated by Django 2.1.3 on 2020-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_multiplechoicequestion_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageQuestion',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='image_url',
        ),
        migrations.AddField(
            model_name='genericquestion',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='genericquestion',
            name='multiple_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='genericquestion',
            name='type',
            field=models.CharField(choices=[('t', 'Text'), ('i', 'Image'), ('v', 'Video')], default='t', max_length=1),
        ),
    ]
