# Generated by Django 2.1.3 on 2020-05-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200507_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericquestion',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
