# Generated by Django 2.1.3 on 2020-05-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20200507_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timerEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='currentScreen',
            field=models.CharField(choices=[('gs', 'Game Start'), ('qs', 'Quiz Start'), ('qe', 'Quiz End'), ('rs', 'Round Start'), ('rt', 'Round Transition'), ('re', 'Round End'), ('qa', 'Question Answering'), ('qm', 'Question Marking')], default='gs', max_length=2),
        ),
    ]
