# Generated by Django 2.1.3 on 2020-05-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200508_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timerLength',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genericquestion',
            name='type',
            field=models.CharField(choices=[('t', 'Text'), ('i', 'Image'), ('v', 'Video'), ('a', 'Audio')], default='t', max_length=1),
        ),
    ]
