# Generated by Django 2.1.3 on 2020-05-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20200513_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='timerLength',
        ),
    ]
