# Generated by Django 2.1.3 on 2020-05-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20200520_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressivestage',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
