# Generated by Django 2.1.3 on 2020-05-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20200520_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressivestage',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
