# Generated by Django 2.1.3 on 2020-05-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_progressivequestion_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressivequestion',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, default=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='progressivequestion',
            name='step',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=10, null=True),
        ),
    ]
