# Generated by Django 2.1.3 on 2020-05-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20200520_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressivequestion',
            name='max_points',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='progressivequestion',
            name='step',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
