# Generated by Django 2.1.3 on 2020-05-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20200520_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgressiveStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.ProgressiveQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userprogressivestage',
            unique_together={('user', 'game')},
        ),
    ]
