# Generated by Django 2.1.3 on 2020-05-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20200521_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogressivestage',
            old_name='stage',
            new_name='current_stage',
        ),
    ]
