# Generated by Django 2.1.3 on 2020-05-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20200521_1839'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogressivestage',
            unique_together={('user', 'game', 'question')},
        ),
    ]
