# Generated by Django 2.1.3 on 2020-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20200521_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericquestion',
            name='question_type',
            field=models.CharField(choices=[('t', 'Text Question'), ('m', 'Multiple Choice Question'), ('p', 'Progressive Question'), ('g', 'Google Trends Question')], default='t', max_length=1),
        ),
    ]
