# Generated by Django 2.1.3 on 2020-06-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20200605_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('correct_ordering', models.PositiveIntegerField()),
                ('display_ordering', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='genericquestion',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='orderingelement',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='quiz.OrderingQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='orderingelement',
            unique_together={('question', 'display_ordering'), ('question', 'correct_ordering')},
        ),
    ]
