# Generated by Django 2.1.3 on 2020-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20200616_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingquestion',
            name='max_points',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='genericquestion',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='genericquestion',
            name='question_type',
            field=models.CharField(choices=[('t', 'Text Question'), ('m', 'Multiple Choice Question'), ('p', 'Progressive Question'), ('g', 'Google Trends Question'), ('o', 'Ordering Question')], default='t', max_length=1),
        ),
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
