# Generated by Django 2.1.3 on 2020-06-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20200616_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(default='world', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='genericquestion',
            name='question_type',
            field=models.CharField(choices=[('t', 'Text Question'), ('m', 'Multiple Choice Question'), ('p', 'Progressive Question'), ('g', 'Google Trends Question'), ('o', 'Ordering Question'), ('m', 'Map Question')], default='t', max_length=1),
        ),
    ]
