# Generated by Django 2.1.3 on 2020-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_auto_20200617_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingquestion',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=45, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderingquestion',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=45, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genericquestion',
            name='question_type',
            field=models.CharField(choices=[('t', 'Text Question'), ('m', 'Multiple Choice Question'), ('p', 'Progressive Question'), ('g', 'Google Trends Question'), ('o', 'Ordering Question'), ('w', 'Map Question')], default='t', max_length=1),
        ),
    ]
