# Generated by Django 2.1.3 on 2020-06-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_auto_20200617_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderingquestion',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='orderingquestion',
            name='lng',
        ),
        migrations.AddField(
            model_name='mapquestion',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=45, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapquestion',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=45, max_digits=9),
            preserve_default=False,
        ),
    ]
