# Generated by Django 2.1.3 on 2020-06-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_auto_20200618_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first', models.PositiveIntegerField()),
                ('second', models.PositiveIntegerField()),
                ('third', models.PositiveIntegerField()),
                ('fourth', models.PositiveIntegerField()),
                ('weighted_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='quiz.User')),
            ],
        ),
    ]
