# Generated by Django 2.1.3 on 2020-06-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_finalresults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalresults',
            options={'verbose_name_plural': 'Final Results'},
        ),
        migrations.AddField(
            model_name='finalresults',
            name='video_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='currentScreen',
            field=models.CharField(choices=[('gs', 'Game Start'), ('qs', 'Quiz Start'), ('qe', 'Quiz End'), ('rs', 'Round Start'), ('rt', 'Round Transition'), ('re', 'Round End'), ('qa', 'Question Answering'), ('qm', 'Question Marking'), ('fr', 'Final Results')], default='gs', max_length=2),
        ),
    ]
